# FABRIC policy requires that code commits are signed with the
# committer's GPG key.
#
# https://github.com/marketplace/actions/check-signed-commits-in-pr
# runs on pull_request_target events.

name: Check signed commits in PR
on: pull_request_target

jobs:
  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      # Allow 1Password/check-signed-commits-action to leave comments
      # on pull requests.
      pull-requests: write

    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
        with:
          comment: |
            ⚠️ This PR contains unsigned commits. To get your PR merged, please sign those commits (`git rebase --exec 'git commit -S --amend --no-edit -n' @{upstream}`) and force push them to this branch (`git push --force-with-lease`).

            If you're new to commit signing, follow the steps below to set up commit signing with `gpg`:

            1. [Generate a GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
            2. [Add the GPG key to your GitHub account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account)
            3. [Configure `git` to use your GPG key for commit signing](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key)
